#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: "us"
    variant: "intl"
  identity:
    hostname: Protofy
    username: protofy
    password: "$6$fuUf4yrDqG.h4caS$9wSQYqUAYUChv4UbvCLs1KNPFo8VFCmnmTVCr0pL/rhiBgC.jkEZOiIKFh4Rurc6u9s.Y/S6OF6oEgoWQY/RY1"
  storage:
    layout:
      name: direct
  packages:
    - openssh-server
  late-commands:
    - "curtin in-target -- systemctl enable ssh"
    - "curtin in-target -- systemctl start ssh"
    - "curtin in-target -- apt-get update -y"
    - "curtin in-target -- apt-get install -y sudo"
    - "curtin in-target -- usermod -aG sudo protofy || true"
    - "echo '%protofy ALL=(ALL) NOPASSWD:ALL' | tee /target/etc/sudoers.d/99-protofy"
    - "curtin in-target -- chmod 440 /etc/sudoers.d/99-protofy"
  updater:
    enable: true
  # This ensures we do not prompt
  # Tells installer not to wait on any questions
  interactive-sections: []

# End of file
